In [11]:
!pip install pyodbc sqlalchemy pandas

Requirement already satisfied: pyodbc in .\.venv\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in .\.venv\Lib\site-packages (2.0.51)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: greenlet>=1 in .\.venv\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pyodbc
import pandas as pd
from sqlalchemy import create_engine

In [13]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=Banking_Case;"
    "Trusted_Connection=yes;"
)

In [14]:
cursor = conn.cursor()

cursor.execute("SELECT @@VERSION")
print(cursor.fetchone()[0])

Microsoft SQL Server 2025 (RTM) - 17.0.1000.7 (X64)
	Oct 21 2025 12:05:57
	Copyright (C) 2025 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Home Single Language 10.0 <X64> (Build 26200: ) (Hypervisor)

In [15]:
query = "select * from customer_info"

In [24]:
df=pd.read_sql(query, conn)
df.head(2)

C:\Users\mishr\AppData\Local\Temp\ipykernel_27944\2197387291.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, conn)

,Client_ID,Name,Age,Location_ID,Banking_Contact,Nationality,Occupation,Fee_Structure,Loyalty_Classification,Estimated_Income,...,Checking_Accounts,Saving_Accounts,Foreign_Currency_Account,Business_Lending,Properties_Owned,Risk_Weighting,Joined_Bank_Date,Gender,Banking_Relationship,Investment_Advisor
0,IND81288,Raymond Mills,24,34324,Anthony Torres,American,Safety Technician IV,High,Jade,75384.77,...,603617.88,607332.46,12249.96,1134475.3,1,2,2019-05-06,Male,Retail,Victor Dean
1,IND65833,Julia Spencer,23,42205,Jonathan Hawkins,African,Software Consultant,High,Jade,289834.31,...,229521.37,344635.16,61162.31,2000526.1,1,3,2001-12-10,Male,Institutional,Jeremy Porter

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Client_ID                 3000 non-null   str
 1   Name                      3000 non-null   str
 2   Age                       3000 non-null   int64
 3   Location_ID               3000 non-null   int64
 4   Banking_Contact           3000 non-null   str
 5   Nationality               3000 non-null   str
 6   Occupation                3000 non-null   str
 7   Fee_Structure             3000 non-null   str
 8   Loyalty_Classification    3000 non-null   str
 9   Estimated_Income          3000 non-null   float64
 10  Superannuation_Savings    3000 non-null   float64
 11  Amount_of_Credit_Cards    3000 non-null   int64
 12  Credit_Card_Balance       3000 non-null   float64
 13  Bank_Loans                3000 non-null   float64
 14  Bank_Deposits             3000 non-null   float64
 15  Checking_Accounts         3000 non-null   float64
 16  Saving_Accounts           3000 non-null   float64
 17  Foreign_Currency_Account  3000 non-null   float64
 18  Business_Lending          3000 non-null   float64
 19  Properties_Owned          3000 non-null   int64
 20  Risk_Weighting            3000 non-null   int64
 21  Joined_Bank_Date          3000 non-null   object
 22  Gender                    3000 non-null   str
 23  Banking_Relationship      3000 non-null   str
 24  Investment_Advisor        3000 non-null   str
dtypes: float64(9), int64(5), object(1), str(10)
memory usage: 586.1+ KB

In [27]:
df.describe()

,Age,Location_ID,Estimated_Income,Superannuation_Savings,Amount_of_Credit_Cards,Credit_Card_Balance,Bank_Loans,Bank_Deposits,Checking_Accounts,Saving_Accounts,Foreign_Currency_Account,Business_Lending,Properties_Owned,Risk_Weighting
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3.000000e+03,3.000000e+03,3.000000e+03,3000.000000,3.000000e+03,3000.000000,3000.000000
mean,51.039667,21563.323000,171305.034263,25531.599673,1.463667,3176.206943,5.913862e+05,6.715602e+05,3.210929e+05,2.329084e+05,29883.529993,8.667598e+05,1.518667,2.249333
std,19.854760,12462.273017,111935.808209,16259.950770,0.676387,2497.094709,4.575570e+05,6.457169e+05,2.820796e+05,2.300078e+05,23109.924010,6.412303e+05,1.102145,1.131191
min,17.000000,12.000000,15919.480000,1482.030000,1.000000,1.170000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,45.000000,0.000000e+00,0.000000,1.000000
25%,34.000000,10803.500000,82906.595000,12513.775000,1.000000,1236.630000,2.396281e+05,2.044004e+05,1.199475e+05,7.479440e+04,11916.542500,3.748251e+05,1.000000,1.000000
50%,51.000000,21129.500000,142313.480000,22357.355000,1.000000,2560.805000,4.797934e+05,4.633165e+05,2.428157e+05,1.640866e+05,24341.190000,7.113147e+05,2.000000,2.000000
75%,69.000000,32054.500000,242290.305000,35464.740000,2.000000,4522.632500,8.258130e+05,9.427546e+05,4.348749e+05,3.155750e+05,41966.392500,1.185110e+06,2.000000,3.000000
max,85.000000,43369.000000,522330.260000,75963.900000,3.000000,13991.990000,2.667557e+06,3.890598e+06,1.969923e+06,1.724118e+06,124704.870000,3.825962e+06,3.000000,5.000000